name: first action example
on: push
jobs:
   first_job:
      runs-on: ubuntu-latest
      steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: welcome message
        run: |
          echo "My first action workflow"
          ls
          cat README.md